#!/usr/bin/env python3
"""Generate the routing catalog (the harness routing projection) for an eval run.

The catalog is the *routing surface* — the discoverable skill name + description
for every skill. It is intentionally NOT part of any frozen task fixture: the
same task fixture is reused across routing conditions, while only the catalog
differs.

Two conditions are supported:

* target-present (default): the catalog contains every skill, including the
  target under test.
* target-absent (``--target-absent <skill>``): the target skill is removed, so
  the harness cannot select it. This measures whether adding the target entry
  changes correct selection.

Usage:
    python3 scripts/build_routing_catalog.py
    python3 scripts/build_routing_catalog.py --target-absent code-review
    python3 scripts/build_routing_catalog.py --format markdown --out catalog.md
"""
import argparse
import glob
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def parse_frontmatter(path):
    text = open(path, encoding="utf-8").read()
    if not text.startswith("---"):
        return None, None
    end = text.find("\n---", 3)
    if end == -1:
        return None, None
    block = text[3:end].strip("\n")
    name = desc = None
    for line in block.splitlines():
        if line.startswith("name:"):
            name = line.split(":", 1)[1].strip().strip('"').strip("'")
        elif line.startswith("description:"):
            desc = line.split(":", 1)[1].strip().strip('"').strip("'")
    return name, desc


def build(target_absent=None):
    rows = []
    for sk in sorted(glob.glob(os.path.join(ROOT, "skills", "*", "SKILL.md"))):
        name, desc = parse_frontmatter(sk)
        if not name:
            continue
        if target_absent and name == target_absent:
            continue
        rows.append((name, desc or ""))
    return rows


def render_markdown(rows):
    out = ["# Skill catalog", "",
           "Neutral routing surface generated by "
           "`scripts/build_routing_catalog.py` from each skill's frontmatter.",
           "It is the harness routing projection, not part of any task fixture.", ""]
    for name, desc in rows:
        out.append(f"- **{name}** — {desc}")
    return "\n".join(out) + "\n"


def render_tsv(rows):
    return "".join(f"{name}\t{desc}\n" for name, desc in rows)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--target-absent", help="skill to omit (baseline condition)")
    ap.add_argument("--format", choices=["markdown", "tsv"], default="markdown")
    ap.add_argument("--out", help="write to this path instead of stdout")
    args = ap.parse_args()

    rows = build(target_absent=args.target_absent)
    text = render_markdown(rows) if args.format == "markdown" else render_tsv(rows)
    if args.out:
        open(args.out, "w", encoding="utf-8").write(text)
        print(f"wrote {args.out} ({len(rows)} skills"
              + (f", target '{args.target_absent}' absent" if args.target_absent else "") + ")",
              file=sys.stderr)
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
